### ISSUE TITLE
content_modified_at in upload_file

### ISSUE THREAD

**Issue by safijari** [sookasa/box.py#14]
Hi,

I should probably do a pull request for this one, but I haven't cloned this repository "properly" yet (new to the whole git thing). I've just been modifying a local copy of client.py as needed.

So, to the point: I think the upload_file function should have a content_modified_at argument, same as the overwrite_file function. This could be important in any bi-directional sync type scenario, where it is important to keep the remote file's "last modified" time the same as that of the one uploaded so that a decision about the sync direction could be made in the future.

I can do a proper pull request for this if necessary. Just let me know how :)

Thanks.

**Comment by tals** [comment]
Feel free to submit a patch (pull request) :)
Just make sure it's tested, and that there are no lint errors (flake8)

**Comment by tals** [comment]
Please open a pull request once it's finished.
See this for details: https://help.github.com/articles/fork-a-repo

**Comment by safijari** [comment]
Will do. I'm currently finishing up the code for an alpha of my app but as soon as I'm done there I will do the pull request. It'll probably take me a little bit to put together a test case though.

In the meantime, I found an error in the file overwrite function (related to the modified date stuff), I'll include the fix for that too.

**Comment by tals** [comment]
Added in a1302f542f
