### ISSUE TITLE
Thumbnail retrieval

### ISSUE THREAD

**Issue by tsanch3z** [sookasa/box.py#26]
I am having some troubles retrieving a file's thumbnail

the **get_thumbnail** function return the _raw_ field of the server's response and I couldn't find a way to get its content. the _read()_ method doesn't return anything even with a specified length and a call to the _data_ field neither.

The only workaround I have found so far is to return the complete response object in **get_thumbnail** so I can get the thumbnail using the _content_ or _text fields_.

Am I missing something about this function usage ?

**Comment by tals** [comment]
Looks like a bug (no Stream=True, so requests just reads out the stream to content). I'll push a fix later!

**Comment by tals** [comment]
Fixed by 335a55901b538eca4f77203668a8c6046e60bce2 (released as 1.2.8).

Thanks for reporting!
