### ISSUE TITLE
Remove support for deprecated v1 API

### ISSUE THREAD

**Issue by sprin** [sookasa/box.py#7]
As I understand it, the v1 API is no longer available:
http://developers.blog.box.com/2013/12/06/one-week-until-the-deadline-for-deprecating-v1-of-the-api/

It would be very nice to drop the now-useless v1 functions, since this package requires lxml just for these functions.

**Comment by tals** [comment]
v1 API might be dead (haven't confirmed), but v1 auth still works (verified just now), which is used in conjunction with v2 api.

v1 auth is significantly nicer to work with compared to v2 due to refresh requirement.

I hate the lxml dependency too :\

**Comment by sprin** [comment]
Ah, was working on the PR before I saw your comment. I wasn't aware that OATH2 was not the only auth option!

OK, probably makes sense  to close this issue until v1 auth is shut down.

**Comment by tals** [comment]
:)
